#!/bin/sh
DIRNAME="`dirname "$0"`"
cd "$DIRNAME"


#./opc-server --config configs/ws281x-24-config.json
#./opc-server --config configs/ws281x-48-config.json
#./opc-server --config configs/apa102-48-config.json
#./opc-server --config configs/ws281x-rj45-config.json
./opc-server --config configs/tedx-orb-config.json
